# Generated by Django 6.0.1 on 2026-02-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_rename_user_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
